sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ajySgR8biuhUmXBgtzaUOYVxKIvnnED8fTifBGIi0dGEFsv19uyiFtsoiqDibirn0rBRKDGxv6eNHp8uOQ2c7lPvK2/qbMI2zsu2xYZ4zXM/cJPpINnvy0dmYOEB17rZYra/GiwUG/f24FjkrXLkr5GHgEjRM9HZEoOhtK4O7/XeiGD4fCjyBRhi0sjLXuvC5ROB1RGIO/2i/aQiUmy8RasMNAVBa4cfodCuh6YFsSMpnAz6os/eq03G+WkP9JN1ynogv1rYOfoEXdvOQutDecfEbDoSRH6tv9yxsIaO032TjWNTzybq/2uhGCb4KPBFtC3zzS1QI9HH4c0aQdRRKiFs7E7BemsrTP3qyqohhjRnN8XE0YAr+04hX7vQg0kCKtEuqmOUh307SFQk0MtUzMBTSXe9VtcSWFC/ava6DdpF9MnT9XvoehtcyIhtAjeY90wQzpVo+G/Y0EdubW/oE+3ZxGUM3/COT96c4K25KcdsoPsCmP8X8KgeCvVtAdX0cjCZS1WQUnu8H47zfU2eJ/D7oRic6LnbCoP2CivzYtyT8EBuLn9Pp0bECBfk/5BQLqCin0CL58b8D85/ySRlCSN+cI5VPOr300TX5L6doUp5lU9scLx124wKuP9pRYFk/rnWr4Y53JONye7FmlzQOiciOCQQlLVB7k/8rYNUL2U=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Two-Poets_1443
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy